init: serde feature
amber-lang/heraclitus pull request #66
Opened 2024-10-11 03:58 UTC by b1ek

ref amber-lang/amber#509

2024-10-15 10:38 UTC, Ph0enixKM commented
I see why this might be useful. Could you @b1ek highlight the advantages that inspired you to create this PR? I'm just curious what exact use case you want to fulfill

2024-10-16 04:23 UTC, b1ek commented
to serialize `Message`s for the amber integrated mode. potentially useful for a very wide range of other things also

2024-10-28 11:32 UTC, Mte90 commented
@b1ek there are conflicts in this PR

2024-11-10 16:51 UTC, Ph0enixKM approved these changes

2024-11-10 16:52 UTC, Ph0enixKM commented
I want others to take a look as well

2024-11-10 19:23 UTC, hdwalters requested changes

2024-11-10 19:23 UTC, hdwalters commented on src/compiling/lexing/lexer.rs
> +#[cfg_attr(feature = "serde", derive(Serialize))]
Should this be `derive(Serialize, Deserialize)` like all the other `cfg_attr` annotations?

2024-11-10 19:23 UTC, hdwalters commented on src/compiling/lexing/reader.rs
> +#[cfg_attr(feature = "serde", derive(Serialize))]
Should this be `derive(Serialize, Deserialize)` like all the other `cfg_attr` annotations?

2024-11-10 19:28 UTC, hdwalters commented
I'm not that familiar with feature support in Rust crates, but it looks like you're creating a new feature in the `heraclitus` crate, which in turn enables serialization/deserialization feature in the `serde` crate. Can I assume you've confirmed that the `amber` project is successfully built against your local `heraclitus` changes, both with and without this feature enabled?

2024-11-14 05:01 UTC, b1ek commented
> Can I assume you've confirmed that the `amber` project is successfully built against your local `heraclitus` changes, both with and without this feature enabled?

that is correct, i tested it before posting the PR

i just tested it now, it breaks some dependency versions with it enabled, but nothing that can't be fixed in 5 minutes

2024-11-14 06:59 UTC, hdwalters approved these changes

2024-11-14 07:46 UTC, merged